In [1]:
from utils.downloader import *
from utils.dataset_reader import *
from utils.extractors import *
from utils.augmentation import *
import torch
import torchvision
import torch.nn as nn
import os

2024-05-27 08:46:09.835673: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-27 08:46:10.532910: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


# TODO
- Aggiungere nella pipeline di preparazione dei dati di pytorch la possibilità di fare da augmentation.
- I logs sono salvati in datasets al momento


# Notebook usage
This notebook is used to streamline as much as possible the data setup for the project. We have trained models on data downloaded from the internet 
as well as present in the Torch and timm libraries. 

This notebook will help you set up the data in the correct directory structure.
It will be used to download the data, extract it, and set it up in the correct directory structure.
If you want to work using datasets preloaded in Torch or timm, you can skip this notebook.

Everything that needs to be edited is marked with "@edit". It is procedural, therefore do not skip steps and go one cell at the time. 

At the moment less common cases such as image folder + .mat file or .csv file are not yet implemented in this notebook (csv function exists) or not implemented at all (.mat function doesn't exist at all)

## Download Data from Kaggle

In [2]:
# manually edit the three following lines, save the dataset wherever you wish, but the "datasets" folder is recommended
# make sure to use the absolute path, not relative
# @edit
#dataset_url = "https://www.kaggle.com/datasets/prasanshasatpathy/soil-types"
dataset_url = "https://www.kaggle.com/datasets/wenewone/cub2002011"
# @edit
root = "/home/disi/ml/datasets"
download_dataset_kaggle(dataset_url, root)
# @edit extract zip
#extract_tgz(f"{dataset_url}/datasets.tar.gz", root)

Dataset URL: https://www.kaggle.com/datasets/wenewone/cub2002011
Kaggle Dataset downloaded successfully.


# Download dataset from a url

In [ ]:
# @edit
dataset_url = "https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz"
root = "/home/disi/ml/datasets"
i = download_dataset(dataset_url, root)
# Manually move it in the datasets folder if you do not need to unzip it, otherwhise extracting it with the following function
# will do it for you
# @edit
extract_tgz(f"{dataset_url}/datasets.tar.gz", root)

## Augment the dataset (optional)

In [ ]:
# @edit
# make sure to add a / in front of the folder name 
dataset_folder = root + "/flowers"
image_generator =  setup_data_generator(rotation_range=40,
                                        width_shift_range=0.2, 
                                        height_shift_range=0.2,
                                        shear_range=0.2, 
                                        zoom_range=0.2, 
                                        horizontal_flip=True, 
                                        fill_mode='nearest')

create_train_val_test_folders(dataset_folder, train_size=0.7, val_size=0.15, test_size=0.15)
cleanup(dataset_folder)

In [ ]:
directory_path  = dataset_folder + "/train"
train_generator = load_data_from_directory(directory_path, target_size=(300,300), batch_size=32)
n_of_batches = 50

#TODO write how the number of batches infuences the actual amount of images generated

In [ ]:
for i, (images, labels) in enumerate(train_generator):
    if i >= n_of_batches:  # Stop after saving images from 50 batches
        break
    save_augmented_images(images, labels, directory_path, train_generator.class_indices)

## Train-Test-Val-Split
If you augmented the images you are good to go, the dataset is ready to be used in the main function. Otherwhise edit and execute the following block of code.


In [7]:
# @edit
# make sure to add a / in front of the folder name 
root = "/home/disi/ml/datasets"
folder_target = f"{root}/CUB_200_2011/images"
dataset_folder = folder_target #+ "/jpg"

In [8]:
create_train_val_test_folders(dataset_folder, train_size=0.7, val_size=0.15, test_size=0.15)

ValueError: With n_samples=0, test_size=0.30000000000000004 and train_size=0.7, the resulting train set will be empty. Adjust any of the aforementioned parameters.

# Datasets from Pytorch

## FGVCAircraft

In [3]:
# @edit
root = "/home/disi/ml/datasets/"
dataset = torchvision.datasets.FGVCAircraft(root=root, download = True)

100%|██████████| 2753340328/2753340328 [00:26<00:00, 103919480.40it/s]


Extracting /home/disi/ml/datasets/fgvc-aircraft-2013b.tar.gz to /home/disi/ml/datasets/


In [4]:
# @edit
dataset_path = f'{root}/fgvc-aircraft-2013b/data/images'
new_dataset_path = f'{root}'
train_txt_path = f'{root}/fgvc-aircraft-2013b/data/images_family_train.txt'
val_txt_path = f'{root}/fgvc-aircraft-2013b/data/images_family_val.txt'
test_txt_path = f'{root}/fgvc-aircraft-2013b/data/images_family_test.txt'

In [5]:
reorganize_dataset_txt(dataset_path, train_txt_path, new_dataset_path, 'train')
reorganize_dataset_txt(dataset_path, val_txt_path, new_dataset_path, 'val')
reorganize_dataset_txt(dataset_path, test_txt_path, new_dataset_path, 'test')

In [10]:
# @edit
cleanup(f'{root}')

Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/149.Brown_Thrasher
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/064.Ring_billed_Gull
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/081.Pied_Kingfisher
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/156.White_eyed_Vireo
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/187.American_Three_toed_Woodpecker
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/104.American_Pipit
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/142.Black_Tern
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/050.Eared_Grebe
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/034.Gray_crowned_Rosy_Finch
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/052.Pied_billed_Grebe
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/132.White_crowned_Sparrow
Deleted folder: /home/disi/ml/datasets/CUB_200_2011/images/089.Hooded_Merganser
Deleted folder: /home/disi/ml

## Flowers102 / Oxford Flowers

In [8]:
# @edit
root = "/home/disi/ml/datasets/"
dataset = torchvision.datasets.Flowers102(root=root, download = True)


100%|██████████| 344862509/344862509 [00:01<00:00, 260280841.69it/s]


Extracting /home/disi/ml/datasets/flowers-102/102flowers.tgz to /home/disi/ml/datasets/flowers-102


100%|██████████| 502/502 [00:00<00:00, 488071.54it/s]


100%|██████████| 14989/14989 [00:00<00:00, 21089709.04it/s]


In [10]:
# Paths to your original dataset, .mat file, and new dataset location
# @edit
dataset_path = f'{root}/flowers-102/jpg'
mat_path = f'{root}/flowers-102/imagelabels.mat'
new_dataset_path = f'{root}'

In [11]:
# Call the function for each of your train, validation, and test sets
reorganize_dataset_mat(dataset_path, mat_path, new_dataset_path, 'train')
reorganize_dataset_mat(dataset_path, mat_path, new_dataset_path, 'val')
reorganize_dataset_mat(dataset_path, mat_path, new_dataset_path, 'test')

In [12]:
# @edit
cleanup(root)

Skipped folder: /home/disi/ml/datasets/val
Deleted folder: /home/disi/ml/datasets/flowers-102
Skipped folder: /home/disi/ml/datasets/train
Skipped folder: /home/disi/ml/datasets/test


# Last step
Once you reach the train-test-val configuration, run this final function to create a folder named as you wish that will contain train-test-val. This will be our root in the main.py. 

In [15]:
# @edit
location = root
newfolder_name = 'Flowers102'
train_folder = f'{location}/train/'
val_folder = f'{location}/val/'
test_folder = f'{location}/test/'
final_structure(location, newfolder_name, train_folder, val_folder, test_folder)

In [ ]:
import os

In [ ]:
img_root = '/home/lorenzo/Desktop/qui/intromlproject_su cui lavorare/datasets/Flowers102'
path = os.path.dirname(img_root) + "/"

In [ ]:
print(img_root)

In [ ]:
folder = os.path.basename(img_root)
print(path)

In [ ]:

# Define the root path
img_root = '/home/disi/ml/intromlproject/datasets/Aerei'

# Standardize the path
standardized_path = os.path.normpath(img_root)

# Split the path into directory and the last component
path, folder = os.path.split(standardized_path)

# Print the results
print("Path:", path)
print("Folder:", folder)

## OXFORD PETS

In [5]:
from torch.utils.data import DataLoader, random_split
import torchvision.transforms as transforms
import torchvision.datasets as datasets

In [23]:
transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.4914, 0.4822, 0.4465], std=[0.2023, 0.1994, 0.2010])
    ])

In [24]:
dataset = datasets.OxfordIIITPet(root="../datasets/",download=True, transform=transform) 

In [25]:
type(dataset)

torchvision.datasets.oxford_iiit_pet.OxfordIIITPet

In [28]:
train_size = int(0.7 * len(dataset))
val_size = int(0.15 * len(dataset))
test_size = len(dataset) - train_size - val_size

In [29]:
train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])

In [30]:
type(train_dataset)

torch.utils.data.dataset.Subset

In [31]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [35]:
for input, label in train_loader:
    print(label)

tensor([24, 29,  4, 21,  3, 30, 12, 18, 22, 27, 28, 20, 22, 15, 18, 13,  0, 18,
        15, 25, 10, 31, 18, 32,  7, 12,  1, 22, 31,  4, 23, 13])
tensor([25, 33, 10, 18, 13, 12, 19,  7, 25, 12, 36, 30, 15, 19, 18, 21,  7, 35,
        17, 34,  0, 33, 20, 33,  3, 27, 22, 10, 13, 25, 26, 20])
tensor([ 9,  3,  0,  9, 12, 21, 10,  9, 29,  6, 13, 23, 17, 14, 22, 13, 26, 27,
         0,  4, 18, 15, 32, 34, 23, 28, 31,  3, 20,  2, 10,  5])
tensor([30, 10,  9, 17, 31, 30,  5, 19, 17, 33, 32,  6,  8,  2,  3, 24, 32, 21,
        29, 34, 16, 29, 30,  4, 25,  2,  8, 24, 25, 28, 28, 18])
tensor([32, 14, 11, 15,  0,  6, 30,  5, 12, 17, 23, 26,  0,  4, 15,  4,  0,  5,
        11, 24, 28,  9, 16, 21, 32, 25, 29, 29, 23, 33, 36, 12])
tensor([15, 13,  0, 19, 14,  8, 10, 20, 30, 20, 22,  0, 25, 17, 25, 15, 17, 21,
         9, 18, 36, 20, 32, 31, 16, 25,  2, 25, 24,  4, 18, 29])
tensor([19, 34, 22, 10, 18, 36,  2, 21,  5, 19,  9, 32,  4, 19, 33, 18, 23, 19,
        32, 29, 14, 29, 13, 15, 31, 29,  9, 11, 33

In [37]:
train_loader.dataset

In [39]:
test_loader